# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('price', models.CharField(max_length=120, null=True)),
                ('image_url', models.CharField(max_length=120, null=True)),
                ('category', models.CharField(max_length=120, null=True)),
                ('sub_category', models.CharField(max_length=120, null=True)),
                ('addr_pr', models.CharField(max_length=120, null=True)),
                ('store', models.CharField(max_length=120, null=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
